### ISSUE TITLE
Additional info

### ISSUE THREAD

**Issue by stroucki** [CMU-HKN/CMU-ECE-CS-Guide#23]
Didn't I take this class with you?

I would add that not only is the class SV heavy, but it is heavy on the verification component. As Nace said, that is where the majority of the jobs are.

I think the key to success is in depth knowledge of hardware threads touched upon in 240, especially the Mealy machine. Keeping state low per hardware thread and planning on paper helps a lot.

Official reference materials were limited for the course, but Nace has several books I saw at office hours that can be obtained through the CMU library that covered a lot of the SV verification language.

After the brutal router project, we did the fun and artistic project with the LED strip.

All projects were individual, except for the partial USB implementation.

I thought router was hardest, but it filled any remaining holes of proficiency for hardware threads and data handoff. The SMP 68k machine took the most work, but the knowledge gained from router made it not-impossible.

I felt so empowered and competent after taking this class. It may have been the best class I have ever taken.
Hope you are doing well.

**Comment by stroucki** [comment]
Talking about 18-340 here.

**Comment by stroucki** [comment]
Talking about 18-341 here.

**Comment by mikinty** [comment]
Hey thanks I appreciate these comments.

I'll add your additions and open a PR
